datadev:
  extends:
    file: docker-compose-common.yml
    service: datadev

db:
  extends:
    file: docker-compose-common.yml
    service: db

cache:
  extends:
    file: docker-compose-common.yml
    service: cache

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - uwsgi

runserver:
  extends:
    file: docker-compose-common.yml
    service: runserver
  environment:
    - DJANGO_MAILGUN_SERVER_NAME=mg.ccgapps.com.au
    - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
    - BASE_REQUEST_LIST=${BASE_REQUEST_LIST} 
    - BPA_MELANOMA_DOWNLOADS_PASSWORD=${BPA_MELANOMA_DOWNLOADS_PASSWORD}
    - BPA_BASE_DOWNLOADS_PASSWORD=${BPA_BASE_DOWNLOADS_PASSWORD}
    - BPA_USERS_DOWNLOADS_PASSWORD=${BPA_USERS_DOWNLOADS_PASSWORD}
    - BPA_GBR_DOWNLOADS_PASSWORD=${BPA_GBR_DOWNLOADS_PASSWORD}
    - BPA_SEPSIS_DOWNLOADS_PASSWORD=${BPA_SEPSIS_DOWNLOADS_PASSWORD}
  volumes_from:
    - datadev
  links:
    - db
    - cache

 
uwsgi:
  extends:
    file: docker-compose-common.yml
    service: uwsgi
  volumes_from:
    - datadev
  links:
    - db
    - cache
    - runserver:web
