datadev:
  extends:
    file: docker-compose-common.yml
    service: datadev

db:
  extends:
    file: docker-compose-common.yml
    service: db

cache:
  extends:
    file: docker-compose-common.yml
    service: cache


runserver:
  extends:
    file: docker-compose-common.yml
    service: runserver
  environment:
    - DJANGO_MAILGUN_SERVER_NAME=mg.ccgapps.com.au
    - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
    - BASE_REQUEST_LIST=${BASE_REQUEST_LIST} 
  volumes_from:
    - datadev
  links:
    - db
    - cache

