# data only container pattern
data:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

db:
  image: mdillon/postgis:9.5
  environment:
    - POSTGRES_USER=webapp
    - POSTGRES_PASSWORD=webapp
  ports:
    - 5432

cache:
  image: memcached:1.4

runserver:
  build: .
  dockerfile: Dockerfile-dev
  command: runserver
  environment:
    - DJANGO_SETTINGS_MODULE=bpam.settings
    - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
    - DJANGO_MAILGUN_SERVER_NAME=${DJANGO_MAILGUN_SERVER_NAME}
    - DBUSER=webapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
  volumes_from:
    - data
  ports:
    - "8000:8000"
  links:
    - db
    - cache
