FROM muccg/python-base:2.7-debian-8
MAINTAINER https://github.com/muccg/bpa-metadata

ENV PROJECT_NAME bpam
ENV PROJECT_SOURCE https://github.com/muccg/bpa-metadata.git
ENV DEPLOYMENT prod
ENV PRODUCTION 1
ENV DEBUG 0
ENV STATIC_ROOT /data/static
ENV WRITABLE_DIRECTORY /data/scratch
ENV MEDIA_ROOT /data/static/media
ENV LOG_DIRECTORY /data/log
ENV DJANGO_SETTINGS_MODULE bpam.settings

RUN env | sort

RUN apt-get update && apt-get install -y --no-install-recommends \
  binutils \
  gdal-bin \
  imagemagick \
  libgeos-c1 \
  libpcre3 \
  libproj-dev \
  libpq5 \
  libxml2 \
  mime-support \
  postgresql-client \
  postgresql-9.4-postgis-2.1 \
  postgresql-9.4-postgis-scripts \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/sh"]
