FROM muccg/bpametadata-base
MAINTAINER https://github.com/muccg/bpa-metadata/

ARG ARG_GIT_TAG

ENV GIT_TAG $ARG_GIT_TAG

ENV DJANGO_SETTINGS_MODULE bpam.prodsettings

ADD build/bpatrack-$GIT_TAG.tar.gz /

EXPOSE 9100 9101
VOLUME ["/data"]

# Drop privileges, set home for ccg-user
USER ccg-user
ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["uwsgi"]
