# data only container pattern
datadev:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/dev:/data

db:
  image: mdillon/postgis:9.5
  environment:
    - POSTGRES_USER=bpamapp
    - POSTGRES_PASSWORD=bpamapp
  ports:
    - 5432

cache:
  image: memcached:1.4

nginx:
  image: muccg/nginx-uwsgi:1.9
  ports:
    - "8443:443"
    - "8080:80"
  volumes:
    - ./data/nginx:/data

runserver:
  image: muccg/bpametadata-dev
  command: runserver
  environment:
    - DJANGO_SETTINGS_MODULE=bpam.settings
    - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
    - DJANGO_MAILGUN_SERVER_NAME=${DJANGO_MAILGUN_SERVER_NAME}
    - DBUSER=webapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
  volumes_from:
    - datadev
  ports:
    - "8000:8000"
  links:
    - db
    - cache

uwsgi:
  image: muccg/bpametadata-dev
  command: uwsgi
  environment:
    - DBUSER=bpamapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_RUNSERVER=1
    # note: important to wait for runserver in dev as both will attempt to syncdb etc
  ports:
    - "9000:9000"
    - "9001:9001"
    - "9100:9100"
    - "9101:9101"
