# data only container pattern
dataprod:
  image: muccg/debian8-base:latest
  volumes:
    - ./data/prod:/data

dbprod:
  extends:
    file: docker-compose-common.yml
    service: db

cacheprod:
  extends:
    file: docker-compose-common.yml
    service: cache

nginxprod:
  hostname: bpam-nginx-prod
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - uwsgiprod:uwsgi

uwsgiprod:
  hostname: bpam-uwsgi-prod
  image: muccg/bpametadata:${GIT_TAG}
  command: uwsgi
  environment:
    - DBUSER=bpamapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - DJANGO_MAILGUN_API_KEY=""
    - DJANGO_MAILGUN_SERVER_NAME=""
  volumes_from:
    - dataprod
  links:
    - dbprod:db
    - cacheprod:cache
