from django.db import models
from django.utils.translation import ugettext_lazy as _

class Sheet(models.Model):
    sheet_number = models.IntegerField("Sheet Number", primary_key=True)
    name_id = models.IntegerField("Name ID", null=True, blank=True)
    family = models.TextField("Family", null=True, blank=True)
    genus = models.TextField("Genus", null=True, blank=True)
    species = models.TextField("Species", null=True, blank=True)
    rank = models.TextField("Rank", null=True, blank=True)
    infraspecies_qualifier = models.TextField("Infraspecies Qualifier", null=True, blank=True)
    infraspecies = models.TextField("Infraspecies", null=True, blank=True)
    author = models.TextField("Author", null=True, blank=True)
    manuscript = models.TextField("Manuscript", null=True, blank=True)
    alien = models.TextField("Alien", null=True, blank=True)
    conservation_code = models.TextField("Conservation Code", null=True, blank=True)
    determiner_name = models.TextField("Determiner Name", null=True, blank=True)
    date_of_determination = models.DateField("Date of Determination", null=True, blank=True)
    determiner_role = models.TextField("Determiner Role", null=True, blank=True)
    name_comment = models.TextField("Name Comment", null=True, blank=True)
    plant_description = models.TextField("Plant Description", null=True, blank=True)
    site_description = models.TextField("Site Description", null=True, blank=True)
    vegetation = models.TextField("Vegetation", null=True, blank=True) 
    frequency = models.TextField("Frequency", null=True, blank=True)
    other_notes = models.TextField("Other Notes", null=True, blank=True)
    locality = models.TextField("Locality", null=True, blank=True)
    state = models.TextField("State", null=True, blank=True)
    latitude = models.FloatField("Latitude", help_text="Degree decimal")
    longitude = models.FloatField("Longitude", help_text="Degree decimal")
    datum = models.TextField("Datum", null=True, blank=True)
    geocode_accuracy = models.IntegerField("Geocode Accuracy", null=True, blank=True)
    geocode_method = models.TextField("Gecode Method", null=True, blank=True)
    barker_coordinate_accuracy_flag = models.IntegerField("Barker Coordinate Accuracy Flag", null=True, blank=True)
    collector = models.TextField("Collector", null=True, blank=True)
    collector_number = models.TextField("Collector Number", null=True, blank=True)
    collection_date = models.DateField("Collection Date", null=True, blank=True)
    voucher = models.TextField("Voucher", null=True, blank=True)
    voucher_id = models.IntegerField("Voucher ID", null=True, blank=True)
    voucher_site = models.TextField("Voucher Site", null=True, blank=True)
    type_status = models.TextField("Type Status", null=True, blank=True)


