FROM muccg/python-base:ubuntu14.04-2.7
MAINTAINER https://github.com/muccg/bpa-metadata

ENV PYTHONUNBUFFERED=1

ARG GIT_TAG=next_release
ENV GIT_TAG $GIT_TAG

ENV DEBIAN_FRONTEND noninteractive
# Project specific deps
RUN apt-get update && apt-get install -y \
  git \
  libpcre3 \
  libpcre3-dev \
  libgeos-c1 \
  libpq-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  python-tk \
  postgresql-client \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN env --unset=DEBIAN_FRONTEND

# install python deps
COPY requirements /app/requirements
WORKDIR /app
RUN pip install -r requirements/runtime-requirements.txt
RUN pip install -r requirements/dev-requirements.txt
RUN pip install -r requirements/test-requirements.txt

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copy code and install the app
COPY . /app
RUN pip install -e bpam

EXPOSE 8000 9000 9001 9100 9101
VOLUME ["/app", "/data"]

ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["runserver"]

