FROM muccg/python-base:ubuntu14.04-2.7
MAINTAINER https://github.com/muccg/bpa-metadata

ENV PYTHONUNBUFFERED=1
ENV APP_RELEASE GITTAG

ENV DEBIAN_FRONTEND noninteractive
# Project specific deps
RUN apt-get update && apt-get install -y \
  git \
  libpcre3 \
  libpcre3-dev \
  libgeos-c1 \
  libpq-dev \
  libssl-dev \
  libxml2-dev \
  libxslt1-dev \
  python-tk \
  postgresql-client \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN env --unset=DEBIAN_FRONTEND

WORKDIR /app
RUN git clone --depth=1 --branch=GITTAG  https://github.com/muccg/bpa-metadata.git .

# install python deps
RUN pip install -r bpam/runtime-requirements.txt
RUN pip install -e bpam

RUN cp docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 8000 9000 9001 9100 9101
VOLUME ["/app", "/data"]

ENV HOME /data
WORKDIR /data

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["runserver"]

